app/Http/routes.php
<?php

Route::resource('/',         'FrontController');

Route::resource('apps',      'AppController');
Route::resource('users',     'UserController');
Route::resource('menus',     'MenuController');
Route::resource('posts',     'PostController');
Route::resource('news',      'NewController');
Route::resource('links',     'LinkController');
Route::resource('log',       'LogController');

Route::get('menus/upgrade/{id}',    'MenuController@upgrade');
Route::get('menus/downgrade/{id}',  'MenuController@downgrade');

Route::get('posts/upgrade/{id}',    'PostController@upgrade');
Route::get('posts/downgrade/{id}',  'PostController@downgrade');

Route::get('allmenus/{id}', 'AppController@getAllMenus');
Route::get('allposts/{id}', 'MenuController@getAllPosts');

Route::get('api/post', 'PostController@getPost')->middleware('cors');

resources/views/apps/create.blade.php
@extends('layouts.apps')
@section('form')
    {!!Form::open(['route'=>'apps.store','method'=>'POST' , 'class'=>'formulario', 'files'=>true])!!}
    <h1 class="text-center">INSTALAR BLOG</h1>
    @include('apps.forms.fields')
    <div class="form-group">
      {!!Form::submit('Guardar', ['class'=>'btn btn-success pull-right'])!!}
    </div>
    {!!Form::close()!!}
@endsection
@section('list')
  @include('apps.list')
@endsection

resources/views/apps/edit.blade.php
@extends('layouts.apps')
@section('form')
  <h1 class="text-center">Actualizar Instalador</h1>
  {!!Form::model($app,['route'=>['apps.update', $app->id], 'method'=>'PUT', 'class'=>'formulario' ,'files'=>true])!!}
    @include('apps.forms.fields')
    <div class="form-group">
      {!!Form::submit('Actualizar usuario', ['class'=>'btn btn-success pull-right'])!!}
    </div>
  {!!Form::close()!!}
@endsection
@section('list')
    @include('apps.list')
@endsection

resources/views/apps/list.blade.php
@if (!empty($apps))
  <h1 class="text-center">BLOGS INSTALADOS</h1>
  <table>
  <thead>
    <th>id</th>
    <th>blog</th>
    <th>Acciones</th>
  </thead>
  @foreach ($apps as $app)
    <tbody>
      <td>{{$app->id}}</td>
      <td>{{$app->slug}}</td>
      <td>
        {!!Form::open(['route'=>['apps.destroy',$app->id], 'method'=>'DELETE'])!!}
        <div class="form-group">
          <a href="{{ route('apps.edit', $app->id) }}"><i class="btn btn-primary glyphicon glyphicon-pencil"></i></a>
            {!! Form::button('<span class="glyphicon glyphicon-trash"></span>',
            [
                'type' => 'button',
                'class'=>'btn btn-danger',
                'onclick' => 'if(confirm("¿Realmente desea eliminar este elemento? ")) {  $(form).submit(); }',
            ]) !!}
        </div>
        {!!Form::close()!!}
      </td>
    </tbody>
  @endforeach
</table>
@endif